alias activate='source bin/activate'
alias aedit='vim ~/.bash_aliases'
alias apply='source ~/.bashrc'
alias aremove='sudo apt-get autoremove'
alias asave='alias > ~/.bash_aliases'
alias cls='clear'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias g='g++ -std=c++11'
alias grep='grep --color=auto'
alias install='sudo apt-get install'
alias ipai='iptables -A INPUT'
alias ipr='cat /etc/iptables.rules | sudo iptables-restore'
alias ips='sudo iptables-save > /etc/iptables.rules'
alias l='ls -CF'
alias la='ls -A'
alias ll='ls -alF'
alias ls='ls --color=auto'
alias ping='ping -c 4'
alias please='sudo $(history -p !!)'
alias python='python3'
alias remove='sudo apt-get remove'
alias rm='echo "Unless you REALLY need it gone, put it in the trash."; false'
alias tp='trash-put'
alias update='sudo apt-get update && sudo apt-get upgrade'
alias upgrade='sudo apt-get upgrade'
alias v='vim'
alias vpa='telnet localhost 7506'
alias vpm='telnet localhost 7505'
